### ISSUE TITLE
4) the presence of screening by barriers; 

### ISSUE THREAD

**Issue by Cmattheou** [geohtet/Noise-Prediction-Algorithm#1]
I am using the latest QGIS version and  version 3.18, and  with both the tool works fine.  Same the tool getting sample data (inside processing toolbox).

I would like to ask how it is possible to import screens or barriers and their attributes ( perhaps height/ absorbing /reflectance) as is one of the Factors For consideration:

the sound power outputs of processes and plant;
the periods of operation of processes and plant;
the distances from sources to receiver;
**the presence of screening by barriers;**
the reflection of sound;
soft ground attenuation.

Many thanks for your great work.

Charalambos Mattheou

**Comment by geohtet** [comment]
Thanks for your interest and great feedback..

Considering barriers is the kind of challenge while I am creating this plugin, barrier calculation was really complex to calculate using a mathematical formula. In this starter version, I just used the 'viewshed analysis' and processive calculation for general purposes. At least, I hope this can give some results for some researchers/project implementors while they are doing project screening, scoping, and other preliminary studies.

Also, this tool should not be used where urban areas with complex elevated buildings and offshore areas although it can give results to users, not reliable.

FYI: version 1.0 doesn't consider the ground attenuation by distance. next version 1.1 will do some calculations using land use data, and its soft & ground percentage.

Regards,
Htet Arkar Soe

**Comment by Cmattheou** [comment]
Thank you very much!
